version: '3.9'

services:
  postgres:
    image: postgres
    container_name: springboot-postgres
    environment:
      - POSTGRES_DB=product_import_db   # Name der Datenbank
      - POSTGRES_USER=postgres          # Benutzername
      - POSTGRES_PASSWORD=admin         # Passwort
    ports:
      - "5432:5432"                     # Port-Weiterleitung: Computer-Port:Container-Port
    volumes:
      - postgres_data:/var/lib/postgresql/data # Speicherort für die Datenbank
      - ./init-scripts:/docker-entrypoint-initdb.d # Ordner mit Initialisierungsskripten

volumes:
  postgres_data: